package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// EmitGoClient renders the typed Go client that callers import. One file
// per entity, packaged by namespace to mirror the server layout:
//
//	gen/go/client/consumer/account_client.go   package consumer
//	gen/go/client/vendor/product_variant_client.go   package vendor
//
// Each per-entity file exposes a typed interface (`AccountClient`) and a
// concrete struct whose method bodies dial through the buf-generated
// `pb.New<Entity>ServiceClient(conn)`. The proto message types ARE the
// value types — callers never see a hand-rolled `Account` struct.
//
// There is no aggregate `Client` struct. With per-namespace packages,
// callers reach for `consumer.NewAccountClient(conn)` directly.
func EmitGoClient(newIR *dsl.IR, cfg GenConfig) ([]GoFile, error) {
	if newIR == nil {
		return nil, fmt.Errorf("EmitGoClient: newIR is required")
	}
	var out []GoFile
	for i := range newIR.Entities {
		e := &newIR.Entities[i]
		f, err := emitGoClientEntity(e, cfg)
		if err != nil {
			return nil, fmt.Errorf("entity %s: %w", e.ID(), err)
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func emitGoClientEntity(e *dsl.Entity, cfg GenConfig) (GoFile, error) {
	if _, err := buildPKSpec(e); err != nil {
		return GoFile{}, err
	}

	var b strings.Builder
	b.WriteString("// Code generated by tidectl. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goNamespace(e.Namespace))

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n\n")
	fmt.Fprintf(&b, "\tpb \"%s/pb/atlantis/%s/v1\"\n", cfg.pbImportPrefix(), goNamespace(e.Namespace))
	b.WriteString(")\n\n")

	ifaceName := e.Name + "Client"

	fmt.Fprintf(&b, "// %s is the typed surface for %s.\n", ifaceName, e.ID())
	fmt.Fprintf(&b, "type %s interface {\n", ifaceName)
	emitClientIfaceMethods(&b, e)
	b.WriteString("}\n\n")

	// Concrete struct dialing through the buf-generated service client.
	// The buf stub already implements every method (its underlying
	// `accountServiceClient` does the gRPC Invoke); our wrapper is one
	// level of indirection that lets us swap clients out for mocks or
	// add cross-cutting behavior (retries, metrics) without touching
	// the buf-generated code.
	concrete := lowerFirst(ifaceName)
	fmt.Fprintf(&b, `// %s wraps the buf-generated %sServiceClient. The wrapper exists so
// caller code talks to one stable interface — swapping clients out for a
// mock or adding cross-cutting behavior (retries, metrics) happens here
// without touching the buf-generated code.
type %s struct {
	inner pb.%sServiceClient
}

// New%s constructs a typed client from a live grpc.ClientConnInterface
// (i.e. anything returned by grpc.NewClient / grpc.Dial).
func New%s(cc grpc.ClientConnInterface) %s {
	return &%s{inner: pb.New%sServiceClient(cc)}
}

`, concrete, e.Name, concrete, e.Name, ifaceName, ifaceName, ifaceName, concrete, e.Name)

	emitClientMethodBodies(&b, e, concrete)

	path := fmt.Sprintf("clients/go/client/%s/%s_client.go", goNamespace(e.Namespace), snakeCase(e.Name))
	return GoFile{Path: path, Content: b.String()}, nil
}

// emitClientIfaceMethods writes the six core methods + per-HNSW search
// onto an interface body. The signatures match what the buf-generated
// service client exposes — we keep grpc.CallOption variadics so callers
// can pass per-call deadlines / retries through.
func emitClientIfaceMethods(b *strings.Builder, e *dsl.Entity) {
	for _, verb := range []string{"Get", "List", "BatchGet", "Create", "Update", "Delete", "Query"} {
		fmt.Fprintf(b, "\t%s%s(ctx context.Context, req *pb.%s%sRequest, opts ...grpc.CallOption) (*pb.%s%sResponse, error)\n",
			verb, e.Name, verb, e.Name, verb, e.Name)
	}
	for _, idx := range e.Indexes {
		if idx.Kind == dsl.IndexHNSW {
			method := fmt.Sprintf("Search%sBy%s", e.Name, snakeToCamel(idx.Field))
			fmt.Fprintf(b, "\t%s(ctx context.Context, req *pb.%sRequest, opts ...grpc.CallOption) (*pb.%sResponse, error)\n",
				method, method, method)
		}
	}
}

// emitClientMethodBodies writes the concrete method implementations.
// Each body is a one-liner that delegates to the buf-generated client.
func emitClientMethodBodies(b *strings.Builder, e *dsl.Entity, concrete string) {
	for _, verb := range []string{"Get", "List", "BatchGet", "Create", "Update", "Delete", "Query"} {
		fmt.Fprintf(b, `func (c *%s) %s%s(ctx context.Context, req *pb.%s%sRequest, opts ...grpc.CallOption) (*pb.%s%sResponse, error) {
	return c.inner.%s%s(ctx, req, opts...)
}

`, concrete, verb, e.Name, verb, e.Name, verb, e.Name, verb, e.Name)
	}
	for _, idx := range e.Indexes {
		if idx.Kind == dsl.IndexHNSW {
			method := fmt.Sprintf("Search%sBy%s", e.Name, snakeToCamel(idx.Field))
			fmt.Fprintf(b, `func (c *%s) %s(ctx context.Context, req *pb.%sRequest, opts ...grpc.CallOption) (*pb.%sResponse, error) {
	return c.inner.%s(ctx, req, opts...)
}

`, concrete, method, method, method, method)
		}
	}
}
