package codegen

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/rachitkumar205/atlantis/internal/codegen/coltype"
	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// EmitEphemerals renders one Go file per namespace that declares any
// `ephemeral` blocks. Each file holds, per ephemeral:
//
//   - A typed value struct with one field per declared field.
//   - Get(ctx, key) (*Value, error) — reads from memcached.
//   - Set(ctx, key, value) error — writes to memcached with the
//     declared TTL.
//   - Delete(ctx, key) error — removes the entry.
//
// The generated code depends on internal/cache/memcached.Client
// (the same client entity caching already uses) and encoding/json
// for value serialization. No Postgres dependency.
func EmitEphemerals(ir *dsl.IR) ([]GoFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitEphemerals: ir is required")
	}
	groups := groupEphemeralsByNamespace(ir)
	if len(groups) == 0 {
		return nil, nil
	}
	out := make([]GoFile, 0, len(groups))
	for _, ns := range sortedEphNSKeys(groups) {
		ephs := groups[ns]
		f, err := emitEphemeralsForNamespace(ns, ephs)
		if err != nil {
			return nil, fmt.Errorf("ephemerals %s: %w", ns, err)
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func groupEphemeralsByNamespace(ir *dsl.IR) map[string][]*dsl.Ephemeral {
	out := map[string][]*dsl.Ephemeral{}
	for i := range ir.Ephemerals {
		e := &ir.Ephemerals[i]
		out[e.Namespace] = append(out[e.Namespace], e)
	}
	for _, group := range out {
		sort.Slice(group, func(i, j int) bool { return group[i].Name < group[j].Name })
	}
	return out
}

func sortedEphNSKeys(m map[string][]*dsl.Ephemeral) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func emitEphemeralsForNamespace(ns string, ephs []*dsl.Ephemeral) (GoFile, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tidectl. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goNamespace(ns))

	needsTime := false
	for _, e := range ephs {
		for _, f := range e.Fields {
			if strings.Contains(coltype.GoType(f.Type, f.NotNull), "time.") {
				needsTime = true
			}
		}
	}

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"github.com/rachitkumar205/atlantis/internal/cache/memcached\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var (\n")
	b.WriteString("\t_ = context.Background\n")
	b.WriteString("\t_ = json.Marshal\n")
	b.WriteString("\t_ = fmt.Sprintf\n")
	if needsTime {
		b.WriteString("\t_ = time.Time{}\n")
	}
	b.WriteString(")\n\n")

	for _, e := range ephs {
		emitOneEphemeral(&b, e)
	}

	path := fmt.Sprintf("gen/go/server/%s/ephemerals.go", goNamespace(ns))
	return GoFile{Path: path, Content: b.String()}, nil
}

func emitOneEphemeral(b *strings.Builder, e *dsl.Ephemeral) {
	// Value struct.
	fmt.Fprintf(b, "// %sValue is the typed shape stored in memcached for %s.\n", e.Name, e.ID())
	fmt.Fprintf(b, "type %sValue struct {\n", e.Name)
	for _, f := range e.Fields {
		if f.Primary {
			continue // key is passed as a separate argument, not stored in the value
		}
		goTyp := coltype.GoType(f.Type, f.NotNull)
		fmt.Fprintf(b, "\t%-30s %s `json:%q`\n", pascalCaseJobField(f.Name), goTyp, f.Name)
	}
	b.WriteString("}\n\n")

	ttl := time.Duration(e.TTLMS) * time.Millisecond
	if ttl == 0 {
		ttl = 24 * time.Hour
	}

	// Store struct wrapping the memcached client.
	fmt.Fprintf(b, "// %sStore provides typed Get/Set/Delete for the %s ephemeral.\n", e.Name, e.ID())
	fmt.Fprintf(b, "type %sStore struct {\n\tMC *memcached.Client\n}\n\n", e.Name)

	// Get.
	fmt.Fprintf(b, "func (s *%sStore) Get(ctx context.Context, key string) (*%sValue, error) {\n", e.Name, e.Name)
	fmt.Fprintf(b, "\tcacheKey := %q + key\n", "eph:"+e.ID()+":")
	b.WriteString("\traw, err := s.MC.Get(ctx, cacheKey)\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(b, "\tvar v %sValue\n", e.Name)
	b.WriteString("\tif err := json.Unmarshal(raw, &v); err != nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"unmarshal ephemeral: %w\", err)\n\t}\n")
	b.WriteString("\treturn &v, nil\n}\n\n")

	// Set.
	fmt.Fprintf(b, "func (s *%sStore) Set(ctx context.Context, key string, v %sValue) error {\n", e.Name, e.Name)
	fmt.Fprintf(b, "\tcacheKey := %q + key\n", "eph:"+e.ID()+":")
	b.WriteString("\traw, err := json.Marshal(v)\n")
	b.WriteString("\tif err != nil {\n\t\treturn fmt.Errorf(\"marshal ephemeral: %w\", err)\n\t}\n")
	fmt.Fprintf(b, "\treturn s.MC.Set(ctx, cacheKey, raw, %d*time.Second)\n", int(ttl.Seconds()))
	b.WriteString("}\n\n")

	// Delete.
	fmt.Fprintf(b, "func (s *%sStore) Delete(ctx context.Context, key string) error {\n", e.Name)
	fmt.Fprintf(b, "\treturn s.MC.Delete(ctx, %q+key)\n", "eph:"+e.ID()+":")
	b.WriteString("}\n\n")
}
