package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/codegen/coltype"
	"github.com/rachitkumar205/atlantis/internal/dsl"
	"github.com/rachitkumar205/atlantis/internal/schema"
)

// GoFile is one emitted Go source file.
type GoFile struct {
	Path    string
	Content string
}

// EmitGoServer renders one server file per entity in newIR. Each file
// satisfies the buf-generated `<Entity>ServiceServer` interface from
// `gen/go/pb/<ns>/`, so the resulting tree can be mounted on a real
// `*grpc.Server` without any adapter shim.
//
// Output layout (per-namespace Go packages):
//
//	gen/go/server/consumer/account_server.go   package consumer
//	gen/go/server/vendor/product_variant_server.go   package vendor
//
// Per-namespace packages fix the historical collision where
// `consumer.CartItem` and `vendor.CartItem` both emitted to
// `package server` with identical Go names.
//
// The emitted code depends on:
//   - github.com/rachitkumar205/atlantis/internal/runtime          — Pool, Cache, Outbox interfaces + conv helpers
//   - github.com/rachitkumar205/atlantis-go/pb/<ns>             — buf-generated proto types
//   - github.com/pgvector/pgvector-go                    — only for entities with vector fields
//   - standard library (context, database/sql, errors, fmt, time)
//
// SQL constants are baked into the file, one per query shape (Get / List /
// BatchGet / Insert / Update / Delete / vector search). Per-entity
// scan/bind helpers are inlined (no reflection on the hot path), matching
// sqlc / Ent / Stripe-internal codegen practice.

// EmittedGoServer is the collected Go source output of one server-emit pass.
type EmittedGoServer struct {
	Files []GoFile
}

// EmitGoServer generates Go server source for every entity in newIR plus
// one top-level `gen/go/server/register.go` aggregator that mounts every
// service onto a `*grpc.Server` in one call.
//
// Adding an entity to the schema → next `make codegen` picks it up, the
// per-entity file appears under gen/go/server/<ns>/, and the aggregator
// rewires automatically. Caller code (`cmd/server/main.go`) imports
// `entityserver "github.com/rachitkumar205/atlantis/gen/go/server"` and calls
// `entityserver.Register(srv, entityserver.ServerDeps{...})` — that line
// never changes.
func EmitGoServer(newIR *dsl.IR) ([]GoFile, error) {
	if newIR == nil {
		return nil, fmt.Errorf("EmitGoServer: newIR is required")
	}
	inboundByEntity := computeInboundRefs(newIR)
	var out []GoFile
	for i := range newIR.Entities {
		e := &newIR.Entities[i]
		f, err := emitGoServerEntity(e, inboundByEntity[e.ID()])
		if err != nil {
			return nil, fmt.Errorf("entity %s: %w", e.ID(), err)
		}
		out = append(out, f)
	}
	out = append(out, emitGoServerRegister(newIR))
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// emitGoServerRegister writes gen/go/server/register.go, the single
// entry point cmd/server/main.go calls to mount every entity service onto
// the gRPC server.
//
// The file is regenerated on every codegen pass and lives in its own
// top-level package `server` (distinct from the per-namespace `consumer`
// and `vendorpkg` sub-packages that hold the per-entity handlers). This
// shape lets main.go import one package, declare one ServerDeps value,
// and call one Register function — adding or removing an entity in the
// DSL never requires editing main.go.
//
// ServerDeps bundles the runtime-tier handles so the constructor list
// stays short. Every emitted New<Entity>Server takes the same four
// arguments, so the aggregator can hand each one ServerDeps's fields
// without per-entity wiring.
func emitGoServerRegister(newIR *dsl.IR) GoFile {
	// Group entities by namespace so the import block lists each
	// namespace once and method calls cluster by namespace for diff
	// stability.
	type entry struct {
		Namespace string
		Entity    string
	}
	byNS := map[string][]entry{}
	namespaces := []string{}
	for i := range newIR.Entities {
		e := &newIR.Entities[i]
		if _, seen := byNS[e.Namespace]; !seen {
			namespaces = append(namespaces, e.Namespace)
		}
		byNS[e.Namespace] = append(byNS[e.Namespace], entry{
			Namespace: e.Namespace,
			Entity:    e.Name,
		})
	}
	sort.Strings(namespaces)

	var b strings.Builder
	b.WriteString("// Code generated by tide. DO NOT EDIT.\n\n")
	b.WriteString("package server\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"google.golang.org/grpc\"\n\n")
	b.WriteString("\t\"github.com/rachitkumar205/atlantis/internal/cache/queryresult\"\n")
	b.WriteString("\t\"github.com/rachitkumar205/atlantis/internal/runtime\"\n\n")
	for _, ns := range namespaces {
		gn := goNamespace(ns)
		fmt.Fprintf(&b, "\t%s \"github.com/rachitkumar205/atlantis/gen/go/server/%s\"\n", gn, gn)
		fmt.Fprintf(&b, "\tpb%s \"github.com/rachitkumar205/atlantis-go/pb/atlantis/%s/v1\"\n", gn, gn)
	}
	b.WriteString(")\n\n")

	b.WriteString(`// ServerDeps bundles the runtime-tier handles every entity server
// receives. Threading one value through Register keeps the call-site
// short and frees the codegen from emitting N-ary constructor wiring.
type ServerDeps struct {
	Pool       runtime.Pool
	Cache      runtime.Cache
	Outbox     runtime.Outbox
	QueryCache *queryresult.Cache
}

// Register mounts every codegen'd entity service onto srv. Regenerated
// from the IR on each codegen pass; do not hand-edit.
func Register(srv *grpc.Server, deps ServerDeps) {
`)
	for _, ns := range namespaces {
		entries := byNS[ns]
		sort.Slice(entries, func(i, j int) bool {
			return entries[i].Entity < entries[j].Entity
		})
		for _, en := range entries {
			gn := goNamespace(en.Namespace)
			fmt.Fprintf(&b, "\tpb%s.Register%sServiceServer(srv, %s.New%sServer(deps.Pool, deps.Cache, deps.Outbox, deps.QueryCache))\n",
				gn, en.Entity, gn, en.Entity)
		}
	}
	// Mount the per-namespace CustomService when any query or
	// procedure exists in that namespace. The Custom server's
	// constructor takes only Pool + Outbox today (custom-result
	// caching is a separate layer scheduled for a follow-up); adding
	// QueryCache later is a non-breaking constructor change.
	customNS := namespacesWithCustom(newIR)
	for _, ns := range customNS {
		gn := goNamespace(ns)
		fmt.Fprintf(&b, "\tpb%s.RegisterCustomServiceServer(srv, %s.NewCustomServer(deps.Pool, deps.Outbox))\n", gn, gn)
	}
	b.WriteString("}\n")

	return GoFile{Path: "gen/go/server/register.go", Content: b.String()}
}

// namespacesWithCustom returns every namespace that owns at least one
// custom query or procedure, in sorted order. Used by the register
// aggregator so it knows which CustomServices to mount.
func namespacesWithCustom(ir *dsl.IR) []string {
	seen := map[string]bool{}
	for i := range ir.Queries {
		seen[namespaceFromID(ir.Queries[i].Owner)] = true
	}
	for i := range ir.Procedures {
		seen[namespaceFromID(ir.Procedures[i].Owner)] = true
	}
	out := make([]string, 0, len(seen))
	for ns := range seen {
		out = append(out, ns)
	}
	sort.Strings(out)
	return out
}

func emitGoServerEntity(e *dsl.Entity, inbound []inboundRef) (GoFile, error) {
	spec, err := buildPKSpec(e)
	if err != nil {
		return GoFile{}, err
	}

	table := qualifiedTable(e)
	allCols := fieldColumns(e)
	insertCols := insertColumns(e)
	insertPlaceholders := insertPlaceholdersFor(e, insertCols)
	updateSets := updateAssignments(e, spec)
	selectList := strings.Join(quoteAll(allCols), ", ")

	var b strings.Builder

	// Header + imports.
	b.WriteString("// Code generated by tide. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goNamespace(e.Namespace))

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"database/sql\"\n")
	b.WriteString("\t\"errors\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"time\"\n\n")
	if e.HasVectorField() {
		b.WriteString("\tpgvector \"github.com/pgvector/pgvector-go\"\n")
	}
	b.WriteString("\t\"google.golang.org/grpc/codes\"\n")
	b.WriteString("\t\"google.golang.org/grpc/status\"\n")
	b.WriteString("\t\"google.golang.org/protobuf/proto\"\n\n")
	fmt.Fprintf(&b, "\tpb \"github.com/rachitkumar205/atlantis-go/pb/atlantis/%s/v1\"\n", goNamespace(e.Namespace))
	b.WriteString("\tcommonpb \"github.com/rachitkumar205/atlantis-go/pb/atlantis/common/v1\"\n")
	b.WriteString("\t\"github.com/rachitkumar205/atlantis/internal/cache/queryresult\"\n")
	b.WriteString("\t\"github.com/rachitkumar205/atlantis/internal/codegen/query\"\n")
	b.WriteString("\t\"github.com/rachitkumar205/atlantis/internal/runtime\"\n")
	b.WriteString(")\n\n")

	// Entities exercise different subsets of these helpers, so blank
	// references silence the unused-import check without branching the
	// import list per entity.
	b.WriteString("var _ = errors.Is\n")
	b.WriteString("var _ = fmt.Sprintf\n")
	b.WriteString("var _ = time.Second\n")
	b.WriteString("var _ = sql.NullString{}\n")
	b.WriteString("var _ = strings.Builder{}\n")
	b.WriteString("var _ = query.FilterSpec{}\n")
	b.WriteString("var _ proto.Message\n")
	b.WriteString("var _ = codes.OK\n")
	b.WriteString("var _ = status.Errorf\n")
	// The back-compat Get/List/BatchGet shims build typed predicates from
	// the common predicates proto. An entity whose PK type has no matching
	// predicate (e.g., timestamp on a composite-PK hypertable) still needs
	// the import so the rest of the wrappers compile; the blank reference
	// keeps `go build` happy if the predicate constructors didn't end up
	// being emitted.
	b.WriteString("var _ = commonpb.StringPredicate{}\n\n")

	serverTypeName := e.Name + "Server"
	b.WriteString("// " + serverTypeName + " is the gRPC handler for " + e.ID() + ".\n")
	b.WriteString("type " + serverTypeName + " struct {\n")
	fmt.Fprintf(&b, "\tpb.Unimplemented%sServiceServer\n", e.Name)
	b.WriteString("\tDB         runtime.Pool\n")
	b.WriteString("\tCache      runtime.Cache\n")
	b.WriteString("\tOutbox     runtime.Outbox\n")
	b.WriteString("\tQueryCache *queryresult.Cache\n")
	b.WriteString("}\n\n")

	b.WriteString("// New" + serverTypeName + " constructs the handler with its runtime dependencies.\n")
	b.WriteString("func New" + serverTypeName + "(db runtime.Pool, cache runtime.Cache, outbox runtime.Outbox, queryCache *queryresult.Cache) *" + serverTypeName + " {\n")
	b.WriteString("\treturn &" + serverTypeName + "{DB: db, Cache: cache, Outbox: outbox, QueryCache: queryCache}\n")
	b.WriteString("}\n\n")

	// SQL constants.
	timeoutMS := e.QueryTimeoutMS
	if timeoutMS == 0 {
		timeoutMS = 2000
	}
	fmt.Fprintf(&b, "const %sQueryTimeoutMS = %d\n\n", lowerFirst(e.Name), timeoutMS)

	softFilter := ""
	if e.SoftDeleteField != "" {
		softFilter = " AND " + quoteIdent(e.SoftDeleteField) + " IS NULL"
	}

	fmt.Fprintf(&b, "const sqlGet%s = `SELECT %s FROM %s WHERE %s%s`\n",
		e.Name, selectList, table, spec.WhereClause(1), softFilter)

	if e.SoftDeleteField != "" {
		fmt.Fprintf(&b, "const sqlList%s = `SELECT %s, COUNT(*) OVER () AS total FROM %s WHERE %s IS NULL ORDER BY %s LIMIT $1 OFFSET $2`\n",
			e.Name, selectList, table, quoteIdent(e.SoftDeleteField), spec.OrderByCols())
	} else {
		fmt.Fprintf(&b, "const sqlList%s = `SELECT %s, COUNT(*) OVER () AS total FROM %s ORDER BY %s LIMIT $1 OFFSET $2`\n",
			e.Name, selectList, table, spec.OrderByCols())
	}

	fmt.Fprintf(&b, "const sqlBatchGet%s = `SELECT %s FROM %s WHERE %s = ANY($1)%s`\n",
		e.Name, selectList, table, quoteIdent(spec.Fields[0].Name), softFilter)

	fmt.Fprintf(&b, "const sqlInsert%s = `INSERT INTO %s (%s) VALUES (%s) RETURNING %s`\n",
		e.Name, table, strings.Join(quoteAll(insertCols), ", "), insertPlaceholders, spec.ReturningCols())

	if updateSets != "" {
		nSetCols := 0
		for _, f := range e.Fields {
			if spec.IsPKColumn(f.Name) || f.Identity || f.Serial {
				continue
			}
			nSetCols++
		}
		fmt.Fprintf(&b, "const sqlUpdate%s = `UPDATE %s SET %s WHERE %s`\n",
			e.Name, table, updateSets, spec.WhereClause(nSetCols+1))
	}

	if e.SoftDeleteField != "" {
		qSoft := quoteIdent(e.SoftDeleteField)
		fmt.Fprintf(&b, "const sqlDelete%s = `UPDATE %s SET %s = now() WHERE %s AND %s IS NULL`\n\n",
			e.Name, table, qSoft, spec.WhereClause(1), qSoft)
	} else {
		fmt.Fprintf(&b, "const sqlDelete%s = `DELETE FROM %s WHERE %s`\n\n",
			e.Name, table, spec.WhereClause(1))
	}

	// FilterSpec is the codegen-time metadata the translator consults to
	// validate filter expressions; one per entity regardless of PK arity.
	// QueryX serves both single-PK and composite-PK entities — the typed
	// predicate surface treats every PK column as just another filterable
	// field, and the keyset cursor naturally extends across multi-column
	// ORDER BYs (see internal/runtime/pagination.go).
	emitFilterSpec(&b, e)

	// Method emitters. The seven RPCs are emitted regardless of PK arity;
	// the per-method emitters branch internally where the wire shape
	// differs (e.g. emitProtoBatchGetMethod's composite-PK path).
	emitProtoGetMethod(&b, e, serverTypeName, spec)
	emitProtoListMethod(&b, e, serverTypeName)
	emitProtoBatchGetMethod(&b, e, serverTypeName, spec)
	emitProtoCreateMethod(&b, e, serverTypeName, spec)
	emitProtoUpdateMethod(&b, e, serverTypeName, spec)
	emitProtoDeleteMethod(&b, e, serverTypeName, spec)
	emitProtoQueryMethod(&b, e, serverTypeName, inbound)
	for _, idx := range e.Indexes {
		if idx.Kind == dsl.IndexHNSW {
			emitProtoVectorSearchMethod(&b, e, serverTypeName, idx)
		}
	}

	// Scan + bind helpers.
	emitScanIntoProto(&b, e)
	emitBindForInsert(&b, e, insertCols)
	if updateSets != "" {
		emitBindForUpdate(&b, e, spec)
	}

	// Compile-time interface satisfaction check.
	fmt.Fprintf(&b, "\nvar _ pb.%sServiceServer = (*%s)(nil)\n", e.Name, serverTypeName)

	path := fmt.Sprintf("gen/go/server/%s/%s_server.go", goNamespace(e.Namespace), snakeCase(e.Name))
	return GoFile{Path: path, Content: b.String()}, nil
}

// pkRequestAccess builds the comma-separated Go expression list that
// pulls each PK column off a Get/Delete request message. Single-PK
// entities yield `req.GetId()`; composite-PK entities yield
// `req.GetCartId(), req.GetVariantId()` (one accessor per column in
// DSL declaration order). Order is significant: it must match the order
// the SQL emitter used to build sqlGet/sqlDelete's $N placeholders.
func pkRequestAccess(spec *pkSpec) string {
	parts := make([]string, len(spec.Fields))
	for i, f := range spec.Fields {
		parts[i] = "req.Get" + snakeToCamel(f.Name) + "()"
	}
	return strings.Join(parts, ", ")
}

// pkEntityAccess is pkRequestAccess's twin for the Update path. Update
// carries the full entity (not a separate PK shell), so the PK columns
// are pulled from `in` rather than `req`.
func pkEntityAccess(spec *pkSpec) string {
	parts := make([]string, len(spec.Fields))
	for i, f := range spec.Fields {
		parts[i] = "in.Get" + snakeToCamel(f.Name) + "()"
	}
	return strings.Join(parts, ", ")
}

// predicateGoName returns the Go type name for the typed predicate that
// matches a DSL field type. Used by the back-compat Get/BatchGet shims
// to build filter messages from caller-supplied PK values. Returns the
// empty string for unfilterable types (vector, array, interval) — those
// can never appear as a PK in the schema, so the shim emitters never
// need to handle them.
//
// Keep in sync with predicateMessageForField (query_emit.go) and
// predicateKindForField (query_emit_server.go) — adding a new filterable
// type means a new arm in all three.
func predicateGoName(t dsl.FieldType) string {
	if t.Array {
		return ""
	}
	switch t.Name {
	case "text", "varchar", "citext", "uuid":
		return "StringPredicate"
	case "numeric":
		return "NumericPredicate"
	case "smallint", "int":
		return "Int32Predicate"
	case "bigint":
		return "Int64Predicate"
	case "boolean":
		return "BoolPredicate"
	case "timestamptz", "date":
		return "TimestampPredicate"
	case "jsonb", "bytea":
		return "BytesPredicate"
	}
	return ""
}

// predicateListGoName returns the *List wrapper type used by the
// predicate's `_In` arm. Used by BatchGet's wrapper to build a typed
// in-list filter. Some predicates have no list arm (NumericPredicate,
// BoolPredicate, TimestampPredicate) — those return "". The single-PK
// BatchGet shim degrades gracefully when this happens by falling back
// to the existing direct-PG path; see emitProtoBatchGetMethod.
func predicateListGoName(t dsl.FieldType) string {
	if t.Array {
		return ""
	}
	switch t.Name {
	case "text", "varchar", "citext", "uuid":
		return "StringList"
	case "smallint", "int":
		return "Int32List"
	case "bigint":
		return "Int64List"
	case "jsonb", "bytea":
		return "BytesList"
	}
	return ""
}

// emitPKEqFilter writes the Go expression that constructs an entity
// Filter populated with `_Eq` predicates on every PK column. The PK
// values come from accessOf(field) — typically `req.Get<Col>()` for the
// Get-shim path. Produces multi-line code rooted at `<varName> :=`.
//
// Composite-PK entities emit one filter field per PK column AND-joined
// implicitly by the translator (every set field on a filter message is
// AND-joined; the OR/NOT composition arms are explicit).
func emitPKEqFilter(b *strings.Builder, e *dsl.Entity, spec *pkSpec, varName string, accessOf func(f *dsl.Field) string) {
	fmt.Fprintf(b, "\t%s := &pb.%sFilter{\n", varName, e.Name)
	for _, f := range spec.Fields {
		pred := predicateGoName(f.Type)
		field := goFieldName(f.Name)
		access := accessOf(f)
		fmt.Fprintf(b, "\t\t%s: &commonpb.%s{Op: &commonpb.%s_Eq{Eq: %s}},\n",
			field, pred, pred, access)
	}
	b.WriteString("\t}\n")
}

func emitProtoGetMethod(b *strings.Builder, e *dsl.Entity, srv string, spec *pkSpec) {
	// Get is a back-compat shim over QueryX so callers using the legacy
	// RPC name still work while we migrate them to QueryX directly. The
	// shim delegates the heavy lifting — typed-filter validation,
	// soft-delete extras, partition-by injection, tier-2 cache — to
	// QueryX, paying one extra hash + memcached round trip on cache
	// misses compared to the previous direct-PG path. The trade is
	// deliberate: one canonical read path means cache invariants are
	// exercised uniformly, and removing this shim later is a single
	// emitter delete.
	fmt.Fprintf(b, `// Get%s implements pb.%sServiceServer.
//
// Deprecated: thin wrapper around Query%s for backwards compatibility. New
// callers should call Query%s directly with a PK-eq filter.
func (s *%s) Get%s(ctx context.Context, req *pb.Get%sRequest) (*pb.Get%sResponse, error) {
`, e.Name, e.Name,
		e.Name, e.Name,
		srv, e.Name, e.Name, e.Name)

	emitPKEqFilter(b, e, spec, "filter", func(f *dsl.Field) string {
		return "req.Get" + snakeToCamel(f.Name) + "()"
	})

	fmt.Fprintf(b, `	qResp, err := s.Query%s(ctx, &pb.Query%sRequest{Filter: filter, Limit: 1})
	if err != nil {
		return nil, err
	}
	if len(qResp.GetEntities()) == 0 {
		return nil, runtime.ErrNotFound
	}
	return &pb.Get%sResponse{Entity: qResp.GetEntities()[0]}, nil
}

`, e.Name, e.Name, e.Name)
}

func emitProtoListMethod(b *strings.Builder, e *dsl.Entity, srv string) {
	// List is a back-compat shim over QueryX. The shim deliberately
	// rejects req.offset > 0 with InvalidArgument: offset-based
	// pagination cannot be mapped onto QueryX's opaque keyset cursor
	// without re-scanning to the offset boundary (slow) or silently
	// returning unstable results under concurrent writes (wrong). This
	// is the Google AIP-158 / Stripe / Supabase pattern: list APIs
	// expose page_token only. Callers using offset must migrate to
	// next_page_token, which the response now carries alongside the
	// legacy total count.
	//
	// The total field stays populated when QueryX returned a count
	// (limit <= 100). For limit > 100 the count is omitted and total is
	// zero — the same wire signal Query uses. Callers that always need a
	// count should call a dedicated Count RPC.
	fmt.Fprintf(b, `// List%s implements pb.%sServiceServer.
//
// Deprecated: thin wrapper around Query%s. Offset-based pagination is
// rejected; use req.page_token (via Query%s) or read resp.next_page_token
// on the next call.
func (s *%s) List%s(ctx context.Context, req *pb.List%sRequest) (*pb.List%sResponse, error) {
	if req.GetOffset() > 0 {
		return nil, status.Errorf(codes.InvalidArgument,
			"List%s.offset is deprecated; use page_token via Query%s")
	}
	qResp, err := s.Query%s(ctx, &pb.Query%sRequest{Limit: req.GetLimit()})
	if err != nil {
		return nil, err
	}
	return &pb.List%sResponse{
		Entities:      qResp.GetEntities(),
		Total:         qResp.GetTotalEstimate(),
		NextPageToken: qResp.GetNextPageToken(),
	}, nil
}

`, e.Name, e.Name,
		e.Name, e.Name,
		srv, e.Name, e.Name, e.Name,
		e.Name, e.Name,
		e.Name, e.Name,
		e.Name)
}

func emitProtoBatchGetMethod(b *strings.Builder, e *dsl.Entity, srv string, spec *pkSpec) {
	if spec.Composite {
		emitProtoBatchGetCompositeMethod(b, e, srv, spec)
		return
	}
	// Single-PK BatchGet wraps QueryX with a typed in-list filter when
	// the PK type has a matching List wrapper (StringList / Int64List /
	// Int32List / BytesList). If the PK type can't ride a typed _In arm
	// (numeric / bool / timestamp), fall back to the direct-PG path so
	// the entity stays callable — bytes/numeric/bool/timestamp PKs
	// aren't covered by the typed _In wrappers, and emitting a broken
	// handler when a schema picks one would be a worse failure mode
	// than the slower direct-PG fallback.
	pkField := spec.Fields[0]
	pred := predicateGoName(pkField.Type)
	list := predicateListGoName(pkField.Type)
	pkGetter := "req.Get" + snakeToCamel(pkField.Name) + "s()"
	pkFilterField := goFieldName(pkField.Name)

	if pred == "" || list == "" {
		// Fallback path: the PK type doesn't have a typed `_In` arm in
		// the predicates proto. Emit the original direct-PG BatchGet so
		// the entity stays callable.
		fmt.Fprintf(b, `// BatchGet%s implements pb.%sServiceServer.
func (s *%s) BatchGet%s(ctx context.Context, req *pb.BatchGet%sRequest) (*pb.BatchGet%sResponse, error) {
	ctx, cancel := runtime.Deadline(ctx, %sQueryTimeoutMS)
	defer cancel()

	rows, err := s.DB.Query(ctx, sqlBatchGet%s, %s)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	resp := &pb.BatchGet%sResponse{}
	for rows.Next() {
		entity := &pb.%s{}
		if err := scanInto%s(rows, entity); err != nil {
			return nil, err
		}
		resp.Entities = append(resp.Entities, entity)
	}
	return resp, rows.Err()
}

`, e.Name, e.Name,
			srv, e.Name, e.Name, e.Name,
			lowerFirst(e.Name),
			e.Name, pkGetter,
			e.Name, e.Name, e.Name)
		return
	}

	// QueryX-wrapped path. The 200-element cap matches query.MaxInListSize
	// (see internal/codegen/query/spec.go) — the translator rejects in
	// lists longer than that anyway, but a clean InvalidArgument from
	// the shim gives callers a more pointed error message than the
	// generic translator rejection. Above 200 IDs, callers should batch
	// or migrate to a streaming pattern.
	fmt.Fprintf(b, `// BatchGet%s implements pb.%sServiceServer.
//
// Deprecated: thin wrapper around Query%s with a PK in-list filter. Caps
// at 200 IDs per call; callers needing more should batch or migrate to
// Query%s directly.
func (s *%s) BatchGet%s(ctx context.Context, req *pb.BatchGet%sRequest) (*pb.BatchGet%sResponse, error) {
	ids := %s
	if len(ids) > 200 {
		return nil, status.Errorf(codes.InvalidArgument,
			"BatchGet%s: at most 200 ids per call (got %%d)", len(ids))
	}
	filter := &pb.%sFilter{
		%s: &commonpb.%s{Op: &commonpb.%s_In{In: &commonpb.%s{Values: ids}}},
	}
	qResp, err := s.Query%s(ctx, &pb.Query%sRequest{Filter: filter, Limit: int32(len(ids))})
	if err != nil {
		return nil, err
	}
	return &pb.BatchGet%sResponse{Entities: qResp.GetEntities()}, nil
}

`, e.Name, e.Name,
		e.Name,
		e.Name,
		srv, e.Name, e.Name, e.Name,
		pkGetter,
		e.Name,
		e.Name,
		pkFilterField, pred, pred, list,
		e.Name, e.Name,
		e.Name)
}

// emitProtoBatchGetCompositeMethod renders a BatchGet that loops over
// the request's *<E>PK list and runs the single-row Get SQL once per
// pair. Composite PKs can't ride one ANY($1) placeholder cheaply; the
// loop costs N round trips but the wire shape stays straightforward
// and BatchGet is rarely the hot path for composite-PK tables.
func emitProtoBatchGetCompositeMethod(b *strings.Builder, e *dsl.Entity, srv string, spec *pkSpec) {
	var pkArgs strings.Builder
	for i, f := range spec.Fields {
		if i > 0 {
			pkArgs.WriteString(", ")
		}
		fmt.Fprintf(&pkArgs, "pk.Get%s()", snakeToCamel(f.Name))
	}
	fmt.Fprintf(b, `// BatchGet%s implements pb.%sServiceServer.
func (s *%s) BatchGet%s(ctx context.Context, req *pb.BatchGet%sRequest) (*pb.BatchGet%sResponse, error) {
	ctx, cancel := runtime.Deadline(ctx, %sQueryTimeoutMS)
	defer cancel()

	resp := &pb.BatchGet%sResponse{}
	for _, pk := range req.GetIds() {
		if pk == nil {
			continue
		}
		entity := &pb.%s{}
		err := scanInto%s(s.DB.QueryRow(ctx, sqlGet%s, %s), entity)
		if err != nil {
			if runtime.IsNoRows(err) {
				continue
			}
			return nil, err
		}
		resp.Entities = append(resp.Entities, entity)
	}
	return resp, nil
}

`, e.Name, e.Name,
		srv, e.Name, e.Name, e.Name,
		lowerFirst(e.Name),
		e.Name,
		e.Name, e.Name, e.Name, pkArgs.String())
}

func emitProtoCreateMethod(b *strings.Builder, e *dsl.Entity, srv string, spec *pkSpec) {
	// The new PK type — same Go type the proto's PK field uses.
	pkGoType := goFieldType(spec.Fields[0].Type, true)

	fmt.Fprintf(b, `// Create%s implements pb.%sServiceServer.
func (s *%s) Create%s(ctx context.Context, req *pb.Create%sRequest) (*pb.Create%sResponse, error) {
	ctx, cancel := runtime.Deadline(ctx, %sQueryTimeoutMS)
	defer cancel()

	in := req.GetEntity()
	if in == nil {
		return nil, fmt.Errorf("Create%s: entity is required")
	}

	tx, err := s.DB.BeginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	args := bindFor%sInsert(in)
	var newPK %s
	if err := tx.QueryRow(ctx, sqlInsert%s, args...).Scan(&newPK); err != nil {
		return nil, err
	}

	cacheID := runtime.CompositeID(newPK)
	cur, _ := s.Cache.CurrentVersion(ctx, %q, cacheID)
	if err := s.Outbox.Enqueue(ctx, tx, %q, cacheID, cur+1); err != nil {
		return nil, err
	}
	if err := s.Outbox.EnqueueGenerationBump(ctx, tx, %q); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	out := &pb.%s{}
	if err := scanInto%s(s.DB.QueryRow(ctx, sqlGet%s, newPK), out); err != nil {
		return nil, err
	}
	return &pb.Create%sResponse{Entity: out}, nil
}

`, e.Name, e.Name,
		srv, e.Name, e.Name, e.Name,
		lowerFirst(e.Name),
		e.Name,
		e.Name,
		pkGoType,
		e.Name,
		e.ID(), e.ID(), e.ID(),
		e.Name, e.Name, e.Name,
		e.Name)
}

func emitProtoUpdateMethod(b *strings.Builder, e *dsl.Entity, srv string, spec *pkSpec) {
	// Update mirrors Delete's `[]any` PK pattern so the body is one
	// template across PK arities. The PK comes off the entity (`in`)
	// rather than a separate request shell — Update's wire shape carries
	// the full entity. CompositeID-encoded args feed both the SQL UPDATE
	// (where the PK predicate occupies the placeholder slots after the
	// SET columns; see sqlUpdate%s) and the post-commit cache /
	// outbox bookkeeping.
	//
	// SET list omits every PK column (see pkSpec.IsPKColumn). For
	// composite-PK + hypertable rows (e.g. vendor.Purchase, partitioned
	// on purchased_at), this means the partitioning column is already
	// excluded from SET, which is what TimescaleDB requires — attempting
	// to UPDATE a partitioning column raises a PG error.
	fmt.Fprintf(b, `// Update%s implements pb.%sServiceServer.
func (s *%s) Update%s(ctx context.Context, req *pb.Update%sRequest) (*pb.Update%sResponse, error) {
	ctx, cancel := runtime.Deadline(ctx, %sQueryTimeoutMS)
	defer cancel()

	in := req.GetEntity()
	if in == nil {
		return nil, fmt.Errorf("Update%s: entity is required")
	}
	id := []any{%s}

	tx, err := s.DB.BeginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	args := bindFor%sUpdate(in, id...)
	tag, err := tx.Exec(ctx, sqlUpdate%s, args...)
	if err != nil {
		return nil, err
	}
	if tag.RowsAffected() == 0 {
		return nil, runtime.ErrNotFound
	}

	cacheID := runtime.CompositeID(id...)
	cur, _ := s.Cache.CurrentVersion(ctx, %q, cacheID)
	if err := s.Outbox.Enqueue(ctx, tx, %q, cacheID, cur+1); err != nil {
		return nil, err
	}
	if err := s.Outbox.EnqueueGenerationBump(ctx, tx, %q); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	out := &pb.%s{}
	if err := scanInto%s(s.DB.QueryRow(ctx, sqlGet%s, id...), out); err != nil {
		return nil, err
	}
	return &pb.Update%sResponse{Entity: out}, nil
}

`, e.Name, e.Name,
		srv, e.Name, e.Name, e.Name,
		lowerFirst(e.Name),
		e.Name,
		pkEntityAccess(spec),
		e.Name, e.Name,
		e.ID(), e.ID(), e.ID(),
		e.Name, e.Name, e.Name,
		e.Name)
}

func emitProtoDeleteMethod(b *strings.Builder, e *dsl.Entity, srv string, spec *pkSpec) {
	// The PK is held as a `[]any` even for single-PK entities so the
	// downstream `tx.Exec` / `runtime.CompositeID` calls splat identically
	// regardless of arity. This is what lets the body of Delete be one
	// template instead of two — splat the slice into sqlDelete's
	// placeholders ($1, or $1 and $2 for composite) and into CompositeID's
	// variadic. CompositeID's length-prefixed encoding (see
	// internal/runtime/runtime.go) is what guarantees that the cache key
	// computed here matches whatever the body / pointer key would be
	// computed as elsewhere, so writes always invalidate the right entry.
	fmt.Fprintf(b, `// Delete%s implements pb.%sServiceServer.
func (s *%s) Delete%s(ctx context.Context, req *pb.Delete%sRequest) (*pb.Delete%sResponse, error) {
	ctx, cancel := runtime.Deadline(ctx, %sQueryTimeoutMS)
	defer cancel()

	id := []any{%s}

	tx, err := s.DB.BeginTx(ctx)
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	tag, err := tx.Exec(ctx, sqlDelete%s, id...)
	if err != nil {
		return nil, err
	}
	if tag.RowsAffected() == 0 {
		return nil, runtime.ErrNotFound
	}

	cacheID := runtime.CompositeID(id...)
	cur, _ := s.Cache.CurrentVersion(ctx, %q, cacheID)
	if err := s.Outbox.Enqueue(ctx, tx, %q, cacheID, cur+1); err != nil {
		return nil, err
	}
	if err := s.Outbox.EnqueueGenerationBump(ctx, tx, %q); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return &pb.Delete%sResponse{}, nil
}

`, e.Name, e.Name,
		srv, e.Name, e.Name, e.Name,
		lowerFirst(e.Name),
		pkRequestAccess(spec),
		e.Name,
		e.ID(), e.ID(), e.ID(),
		e.Name)
}

func emitProtoVectorSearchMethod(b *strings.Builder, e *dsl.Entity, srv string, idx dsl.Index) {
	method := fmt.Sprintf("Search%sBy%s", e.Name, snakeToCamel(idx.Field))
	op := vectorDistanceOp(idx.VecOps)
	sqlConst := "sql" + method
	qVec := quoteIdent(idx.Field)
	selectList := strings.Join(quoteAll(fieldColumns(e)), ", ")

	fmt.Fprintf(b, "const %s = `SELECT %s, %s %s $1::vector AS distance FROM %s ORDER BY %s %s $1::vector LIMIT $2`\n\n",
		sqlConst, selectList, qVec, op, qualifiedTable(e), qVec, op)

	fmt.Fprintf(b, `// %s implements pb.%sServiceServer.
func (s *%s) %s(ctx context.Context, req *pb.%sRequest) (*pb.%sResponse, error) {
	ctx, cancel := runtime.Deadline(ctx, %sQueryTimeoutMS)
	defer cancel()

	queryVec := pgvector.NewVector(req.GetQueryVector())
	rows, err := s.DB.Query(ctx, %s, queryVec, req.GetLimit())
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	resp := &pb.%sResponse{}
	for rows.Next() {
		entity := &pb.%s{}
		var dist float32
		if err := scanInto%sWithDistance(rows, entity, &dist); err != nil {
			return nil, err
		}
		resp.Entities = append(resp.Entities, entity)
		resp.Distances = append(resp.Distances, dist)
	}
	return resp, rows.Err()
}

`, method, e.Name,
		srv, method, method, method,
		lowerFirst(e.Name),
		sqlConst,
		method,
		e.Name, e.Name)
}

// emitScanIntoProto writes scanInto<Entity>, scanInto<Entity>WithTotal,
// and scanInto<Entity>WithDistance. Each one scans a row in SELECT order
// (matching fieldColumns) into proto fields, using sql.NullX for nullable
// scalars and pgvector.Vector for vector columns.
func emitScanIntoProto(b *strings.Builder, e *dsl.Entity) {
	// Per-field scan locals + post-assign logic.
	var (
		localDecls  []string // "var emailLocal string"
		scanTargets []string // "&emailLocal"
		postAssigns []string // "out.Email = emailLocal"
	)
	for _, f := range e.Fields {
		local, target, assign := protoScanFragments(f)
		localDecls = append(localDecls, local)
		scanTargets = append(scanTargets, target)
		postAssigns = append(postAssigns, assign)
	}

	indent := "\t"
	indentedDecls := indent + strings.Join(localDecls, "\n"+indent)
	indentedAssigns := indent + strings.Join(postAssigns, "\n"+indent)

	fmt.Fprintf(b, `func scanInto%s(src interface{ Scan(dest ...any) error }, out *pb.%s) error {
%s
	if err := src.Scan(%s); err != nil {
		return err
	}
%s
	return nil
}

`,
		e.Name, e.Name,
		indentedDecls,
		strings.Join(scanTargets, ", "),
		indentedAssigns,
	)

	fmt.Fprintf(b, `func scanInto%sWithTotal(src interface{ Scan(dest ...any) error }, out *pb.%s, total *int64) error {
%s
	if err := src.Scan(%s, total); err != nil {
		return err
	}
%s
	return nil
}

`,
		e.Name, e.Name,
		indentedDecls,
		strings.Join(scanTargets, ", "),
		indentedAssigns,
	)

	fmt.Fprintf(b, `func scanInto%sWithDistance(src interface{ Scan(dest ...any) error }, out *pb.%s, distance *float32) error {
%s
	if err := src.Scan(%s, distance); err != nil {
		return err
	}
%s
	return nil
}

`,
		e.Name, e.Name,
		indentedDecls,
		strings.Join(scanTargets, ", "),
		indentedAssigns,
	)
}

// protoScanFragments returns the three lines the scan helper needs for
// one entity field: the local declaration, the rows.Scan target, and
// the post-scan assignment. Local name and protoField LHS follow the
// entity-server naming convention (`fooLocal` / `out.Foo`) so the
// emitted Go is readable next to the buf-generated struct.
func protoScanFragments(f dsl.Field) (decl, target, assign string) {
	local := lowerFirst(goFieldName(f.Name)) + "Local"
	protoField := "out." + goFieldName(f.Name)
	// Match the proto-emit rule: NOT NULL with declared DEFAULT is generated
	// as `optional`, so the proto field is a pointer. The scan layer must
	// produce a pointer assignment too, or the generated code fails to
	// compile with "cannot use <type> as *<type>".
	notNull := f.NotNull
	if f.Default != nil {
		notNull = false
	}
	return coltype.ScanFragments(f.Type, notNull, local, protoField)
}

// emitBindForInsert writes bindFor<Entity>Insert(in *pb.<Entity>) []any.
// Returns the positional bind args in the order of insertCols (which
// already excludes Identity/Serial columns).
func emitBindForInsert(b *strings.Builder, e *dsl.Entity, insertCols []string) {
	fmt.Fprintf(b, `func bindFor%sInsert(in *pb.%s) []any {
	return []any{
`, e.Name, e.Name)

	for _, colName := range insertCols {
		f := e.FindField(colName)
		if f == nil {
			fmt.Fprintf(b, "\t\tnil, // column %q not found on entity — codegen bug\n", colName)
			continue
		}
		fmt.Fprintf(b, "\t\t%s,\n", protoBindExpr(*f))
	}
	b.WriteString("\t}\n}\n\n")
}

// emitBindForUpdate writes bindFor<Entity>Update(in *pb.<Entity>, pk ...any) []any.
// The PK args come after the SET column args so the placeholder offsets
// in sqlUpdate<Entity> match. Variadic on the PK lets one signature
// serve both single-PK ($N) and composite-PK ($N, $N+1, …) entities;
// the caller splats a []any holding the PK columns in DSL declaration
// order, which is the same order the SQL emitter used when building the
// WHERE clause.
func emitBindForUpdate(b *strings.Builder, e *dsl.Entity, spec *pkSpec) {
	fmt.Fprintf(b, `func bindFor%sUpdate(in *pb.%s, pk ...any) []any {
	args := []any{
`, e.Name, e.Name)

	for _, f := range e.Fields {
		if spec.IsPKColumn(f.Name) || f.Identity || f.Serial {
			continue
		}
		fmt.Fprintf(b, "\t\t%s,\n", protoBindExpr(f))
	}
	b.WriteString("\t}\n\treturn append(args, pk...)\n}\n\n")
}

// protoBindExpr returns the Go expression that turns a proto field on
// `in` into the value pgx needs for bind, using the entity-server
// naming convention for getter and pointer references.
func protoBindExpr(f dsl.Field) string {
	protoGetter := "in.Get" + goFieldName(f.Name) + "()"
	protoFieldPtr := "in." + goFieldName(f.Name)
	// NOT NULL columns with a declared DEFAULT are emitted as `optional`
	// in the proto (see proto.go) so the caller can omit them and let
	// the INSERT's COALESCE fire the default. On the bind side that
	// means the proto field is a pointer; route through the same
	// Nullable helpers the nullable case uses so the bound value lands
	// as NULL (not the Go zero value) when the caller didn't set it.
	notNull := f.NotNull
	if f.Default != nil {
		notNull = false
	}
	return coltype.BindExpr(f.Type, notNull, protoGetter, protoFieldPtr)
}

// pkSpec describes the primary key of an entity for the server emitter. It
// hides the single-vs-composite split behind one set of accessor methods
// so every emit*Method can reach for the same vocabulary regardless of
// arity.
//
// Built once per entity at the top of emitGoServerEntity.
type pkSpec struct {
	// Composite is true when the PK has more than one column (declared via
	// `primary by col1, col2, ...` on the entity).
	Composite bool
	// Fields lists PK columns in DSL declaration order. CompositeID encoding
	// depends on this order — reorder = wire-shape change.
	Fields []*dsl.Field
	// EntityName is the user-facing entity name; the composite PK struct
	// type is `<EntityName>PK`.
	EntityName string
}

func buildPKSpec(e *dsl.Entity) (*pkSpec, error) {
	if len(e.CompositePK) > 0 {
		fields := make([]*dsl.Field, 0, len(e.CompositePK))
		for _, name := range e.CompositePK {
			f := e.FindField(name)
			if f == nil {
				return nil, fmt.Errorf("composite PK references unknown field %q", name)
			}
			fields = append(fields, f)
		}
		return &pkSpec{Composite: true, Fields: fields, EntityName: e.Name}, nil
	}
	pk := e.PrimaryField()
	if pk == nil {
		return nil, fmt.Errorf("no primary field")
	}
	return &pkSpec{Composite: false, Fields: []*dsl.Field{pk}, EntityName: e.Name}, nil
}

// IsPKColumn reports whether name is one of the PK columns. Used to skip
// PK fields in the UPDATE SET list.
func (p *pkSpec) IsPKColumn(name string) bool {
	for _, f := range p.Fields {
		if f.Name == name {
			return true
		}
	}
	return false
}

// ReturnType is the Go type used as Create's return + the type referenced
// in handler signatures. Single PK: the scalar Go type. Composite: the
// generated wrapper struct (`<Entity>PK`).
func (p *pkSpec) ReturnType() string {
	if p.Composite {
		return p.EntityName + "PK"
	}
	return goFieldType(p.Fields[0].Type, true)
}

// SigParam returns the parameter declaration as it appears in the method
// signature: `id int64` (single) or `pk AccountSessionPK` (composite).
func (p *pkSpec) SigParam() string {
	if p.Composite {
		return "pk " + p.EntityName + "PK"
	}
	return "id " + goFieldType(p.Fields[0].Type, true)
}

// CallArgs returns the comma-separated Go expressions that pass PK values
// into a SQL query.
func (p *pkSpec) CallArgs() string {
	if !p.Composite {
		return "id"
	}
	parts := make([]string, len(p.Fields))
	for i, f := range p.Fields {
		parts[i] = "pk." + goFieldName(f.Name)
	}
	return strings.Join(parts, ", ")
}

// WhereClause returns the SQL predicate that matches one row by PK,
// starting at placeholder $startIdx.
func (p *pkSpec) WhereClause(startIdx int) string {
	if !p.Composite {
		return fmt.Sprintf("%s = $%d", quoteIdent(p.Fields[0].Name), startIdx)
	}
	cols := make([]string, len(p.Fields))
	ph := make([]string, len(p.Fields))
	for i, f := range p.Fields {
		cols[i] = quoteIdent(f.Name)
		ph[i] = fmt.Sprintf("$%d", startIdx+i)
	}
	return "(" + strings.Join(cols, ", ") + ") = (" + strings.Join(ph, ", ") + ")"
}

// OrderByCols renders the ORDER BY column list.
func (p *pkSpec) OrderByCols() string {
	cols := make([]string, len(p.Fields))
	for i, f := range p.Fields {
		cols[i] = quoteIdent(f.Name)
	}
	return strings.Join(cols, ", ")
}

// ReturningCols mirrors OrderByCols.
func (p *pkSpec) ReturningCols() string { return p.OrderByCols() }

// CountPlaceholders returns the number of $N tokens the PK consumes.
func (p *pkSpec) CountPlaceholders() int { return len(p.Fields) }

// fieldColumns delegates to the shared schema package.
func fieldColumns(e *dsl.Entity) []string {
	return schema.FieldColumns(e)
}

// insertColumns delegates to the shared schema package.
func insertColumns(e *dsl.Entity) []string {
	return schema.InsertColumns(e)
}

// insertPlaceholdersFor builds the VALUES clause for sqlInsert<Entity>.
// For columns with a declared SQL DEFAULT, the placeholder is wrapped in
// COALESCE($N::<type>, <default-expr>) so that an unset proto field (which
// binds as NULL via the runtime.NullableX helpers) resolves to the column
// default at INSERT time instead of writing literal NULL. The cast is
// required because Postgres can't infer the parameter type when the
// placeholder is the first arg to COALESCE alongside a literal of a
// different shape.
//
// For columns without a default, the placeholder is the plain $N. Order
// matches insertCols so bind args still line up positionally.
func insertPlaceholdersFor(e *dsl.Entity, insertCols []string) string {
	parts := make([]string, len(insertCols))
	for i, name := range insertCols {
		f := e.FindField(name)
		ph := fmt.Sprintf("$%d", i+1)
		if f != nil && f.Default != nil {
			parts[i] = fmt.Sprintf("COALESCE(%s::%s, %s)", ph, sqlType(f.Type), defaultExpr(*f.Default))
			continue
		}
		parts[i] = ph
	}
	return strings.Join(parts, ", ")
}

// updateAssignments renders the "col1 = $1, col2 = $2, ..." body of UPDATE.
func updateAssignments(e *dsl.Entity, spec *pkSpec) string {
	parts := []string{}
	i := 0
	for _, f := range e.Fields {
		if spec.IsPKColumn(f.Name) {
			continue
		}
		if f.Identity || f.Serial {
			continue
		}
		i++
		parts = append(parts, fmt.Sprintf("%s = $%d", quoteIdent(f.Name), i))
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, ", ")
}

// quoteAll delegates to the shared schema package.
func quoteAll(ids []string) []string {
	return schema.QuoteAll(ids)
}

func goFieldName(snake string) string { return snakeToCamel(snake) }

// goFieldType is a thin wrapper that keeps the historical call sites
// (composite-PK struct fields, HNSW search method queryVec parameter)
// stable while routing every type-mapping decision through coltype.
// NOT for proto field types — those come from buf-generated code.
func goFieldType(t dsl.FieldType, notNull bool) string {
	return coltype.GoType(t, notNull)
}

func vectorDistanceOp(ops dsl.VectorOps) string {
	switch ops {
	case dsl.VecOpsCosine:
		return "<=>"
	case dsl.VecOpsL2:
		return "<->"
	case dsl.VecOpsIP:
		return "<#>"
	}
	return "<=>"
}

// lowerFirst lower-cases the first rune of a string.
func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	if s[0] >= 'A' && s[0] <= 'Z' {
		return string(s[0]+'a'-'A') + s[1:]
	}
	return s
}
