package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/rachitkumar205/atlantis/internal/codegen/coltype"
	"github.com/rachitkumar205/atlantis/internal/dsl"
)

// EmitWorkflows renders one Go file per namespace that declares any
// `workflow` blocks. Each file holds, per workflow:
//
//   - A typed State struct with one field per state field in the DSL.
//   - A WorkflowName const matching the IR id.
//   - Step/compensation name constants for caller reference.
func EmitWorkflows(ir *dsl.IR) ([]GoFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("EmitWorkflows: ir is required")
	}
	groups := groupWorkflowsByNamespace(ir)
	if len(groups) == 0 {
		return nil, nil
	}
	out := make([]GoFile, 0, len(groups))
	for _, ns := range sortedWFNamespaceKeys(groups) {
		wfs := groups[ns]
		f, err := emitWorkflowsForNamespace(ns, wfs)
		if err != nil {
			return nil, fmt.Errorf("workflows %s: %w", ns, err)
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

func groupWorkflowsByNamespace(ir *dsl.IR) map[string][]*dsl.Workflow {
	out := map[string][]*dsl.Workflow{}
	for i := range ir.Workflows {
		w := &ir.Workflows[i]
		out[w.Namespace] = append(out[w.Namespace], w)
	}
	for _, group := range out {
		sort.Slice(group, func(i, j int) bool { return group[i].Name < group[j].Name })
	}
	return out
}

func sortedWFNamespaceKeys(m map[string][]*dsl.Workflow) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func emitWorkflowsForNamespace(ns string, wfs []*dsl.Workflow) (GoFile, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tide. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", goNamespace(ns))

	needsTime := false
	for _, wf := range wfs {
		for _, f := range wf.State {
			if strings.Contains(coltype.GoType(f.Type, f.NotNull), "time.") {
				needsTime = true
				break
			}
		}
		if needsTime {
			break
		}
	}

	b.WriteString("import (\n")
	if needsTime {
		b.WriteString("\t\"time\"\n\n")
	}
	b.WriteString("\t_ \"encoding/json\"\n")
	b.WriteString(")\n\n")
	if needsTime {
		b.WriteString("var _ = time.Time{}\n\n")
	}

	for _, wf := range wfs {
		emitOneWorkflow(&b, wf)
	}

	path := fmt.Sprintf("gen/go/server/%s/workflows.go", goNamespace(ns))
	return GoFile{Path: path, Content: b.String()}, nil
}

func emitOneWorkflow(b *strings.Builder, wf *dsl.Workflow) {
	id := wf.ID()

	// State struct.
	fmt.Fprintf(b, "// %sState is the typed state for the %s workflow.\n", wf.Name, id)
	fmt.Fprintf(b, "type %sState struct {\n", wf.Name)
	for _, f := range wf.State {
		goTyp := coltype.GoType(f.Type, f.NotNull)
		fmt.Fprintf(b, "\t%-30s %s `json:%q`\n", pascalCaseJobField(f.Name), goTyp, f.Name)
	}
	b.WriteString("}\n\n")

	// WorkflowName const.
	fmt.Fprintf(b, "const %sWorkflowName = %q\n\n", wf.Name, id)

	// Step name constants.
	if len(wf.Steps) > 0 {
		fmt.Fprintf(b, "// %s step names.\n", wf.Name)
		fmt.Fprintf(b, "const (\n")
		for _, s := range wf.Steps {
			fmt.Fprintf(b, "\t%sStep%s = %q\n", wf.Name, pascalCaseJobField(s.Name), s.Name)
		}
		fmt.Fprintf(b, ")\n\n")
	}
}
